#!/bin/bash

function pack {
cat <<__EOF__ > $2
#!/usr/bin/env node
$(cat $1)
__EOF__
chmod +x $2
}

function compile {
	local SRC=$1
	local DST=$2
	local TMP1=$(mktemp /tmp/XXXXXX)
	local TMP2=$(mktemp /tmp/XXXXXX)
	echo "bundling ${SRC}"
	NODE_PATH=$(pwd)/node_modules browserify --node --outfile ${TMP1} ${SRC} | awk '{printf "\t%s\n", $0}'
	echo "minimizing ${SRC}"
	uglifyjs --compress --mangle -p 5 --output ${TMP2} ${TMP1} 2>&1 | awk '{printf "\t%s\n", $0}'
	echo "output ${DST}"
	pack ${TMP2} ${DST}
	rm -f ${TMP1}
	rm -f ${TMP2}
	# browserify --node --extension=ls -t browserify-livescript --outfile ${TMP1} --full-paths ${SRC}
	# discify ${TMP1} > /tmp/aa.html
	# rm -f ${TMP1}
}

[ "" == "$(which browserify)" ] && echo "please install browserify first" && exit 1
[ "" == "$(which uglifyjs)" ] && echo "please install uglifyjs first" && exit 1

CURRENT=$(pwd)
cd $(dirname $0)
mkdir $(pwd)/work
EXECUTABLE="$(pwd)/work/$(basename $(pwd))"
compile "$(pwd)/server.js" ${EXECUTABLE}
chmod +x ${EXECUTABLE}
